//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPortal.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pridať nové.
        /// </summary>
        public static string Btn_Add {
            get {
                return ResourceManager.GetString("Btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Späť.
        /// </summary>
        public static string Btn_Back {
            get {
                return ResourceManager.GetString("Btn_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušiť.
        /// </summary>
        public static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvoriť.
        /// </summary>
        public static string Btn_Create {
            get {
                return ResourceManager.GetString("Btn_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmazať.
        /// </summary>
        public static string Btn_Delete {
            get {
                return ResourceManager.GetString("Btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Btn_Detail {
            get {
                return ResourceManager.GetString("Btn_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upraviť.
        /// </summary>
        public static string Btn_Edit {
            get {
                return ResourceManager.GetString("Btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Btn_Ok {
            get {
                return ResourceManager.GetString("Btn_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložiť.
        /// </summary>
        public static string Btn_Save {
            get {
                return ResourceManager.GetString("Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavenia.
        /// </summary>
        public static string Btn_Settings {
            get {
                return ResourceManager.GetString("Btn_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavenie parametrov systému.
        /// </summary>
        public static string Config_PageTitle {
            get {
                return ResourceManager.GetString("Config_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametre.
        /// </summary>
        public static string Config_TableTitle {
            get {
                return ResourceManager.GetString("Config_TableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        public static string Customer_Address {
            get {
                return ResourceManager.GetString("Customer_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo.
        /// </summary>
        public static string Customer_AddressBuildingNumber {
            get {
                return ResourceManager.GetString("Customer_AddressBuildingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesto.
        /// </summary>
        public static string Customer_AddressCity {
            get {
                return ResourceManager.GetString("Customer_AddressCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Štát.
        /// </summary>
        public static string Customer_AddressCountry {
            get {
                return ResourceManager.GetString("Customer_AddressCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulica.
        /// </summary>
        public static string Customer_AddressStreet {
            get {
                return ResourceManager.GetString("Customer_AddressStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSČ.
        /// </summary>
        public static string Customer_AddressZipCode {
            get {
                return ResourceManager.GetString("Customer_AddressZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo účtu IBAN.
        /// </summary>
        public static string Customer_BankAccountIBAN {
            get {
                return ResourceManager.GetString("Customer_BankAccountIBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvoriť novú PO - právnickú osobu .
        /// </summary>
        public static string Customer_CompanyCreateDialogTitle {
            get {
                return ResourceManager.GetString("Customer_CompanyCreateDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podrobnosti.
        /// </summary>
        public static string Customer_CompanyDetailDialogTitle {
            get {
                return ResourceManager.GetString("Customer_CompanyDetailDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upraviť PO - právnickú osobu.
        /// </summary>
        public static string Customer_CompanyEditDialogTitle {
            get {
                return ResourceManager.GetString("Customer_CompanyEditDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IČO.
        /// </summary>
        public static string Customer_CompanyID {
            get {
                return ResourceManager.GetString("Customer_CompanyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Názov.
        /// </summary>
        public static string Customer_CompanyName {
            get {
                return ResourceManager.GetString("Customer_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIČ.
        /// </summary>
        public static string Customer_CompanyTAXID {
            get {
                return ResourceManager.GetString("Customer_CompanyTAXID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ.
        /// </summary>
        public static string Customer_CompanyType {
            get {
                return ResourceManager.GetString("Customer_CompanyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IČ DPH.
        /// </summary>
        public static string Customer_CompanyVATID {
            get {
                return ResourceManager.GetString("Customer_CompanyVATID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Customer_ContactEmail {
            get {
                return ResourceManager.GetString("Customer_ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mob. číslo.
        /// </summary>
        public static string Customer_ContactMobile {
            get {
                return ResourceManager.GetString("Customer_ContactMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel. číslo.
        /// </summary>
        public static string Customer_ContactPhone {
            get {
                return ResourceManager.GetString("Customer_ContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web stránka.
        /// </summary>
        public static string Customer_ContactWeb {
            get {
                return ResourceManager.GetString("Customer_ContactWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ.
        /// </summary>
        public static string Customer_CustomerType {
            get {
                return ResourceManager.GetString("Customer_CustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naozaj chcete odstrániť tohto zákazníka?.
        /// </summary>
        public static string Customer_DeleteDialogSure {
            get {
                return ResourceManager.GetString("Customer_DeleteDialogSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmazať.
        /// </summary>
        public static string Customer_DeleteDialogTitle {
            get {
                return ResourceManager.GetString("Customer_DeleteDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvoriť novú FO - fyzickú osobu.
        /// </summary>
        public static string Customer_IndividualCreateDialogTitle {
            get {
                return ResourceManager.GetString("Customer_IndividualCreateDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podrobnosti.
        /// </summary>
        public static string Customer_IndividualDetailDialogTitle {
            get {
                return ResourceManager.GetString("Customer_IndividualDetailDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upraviť FO - fyzickú osobu.
        /// </summary>
        public static string Customer_IndividualEditDialogTitle {
            get {
                return ResourceManager.GetString("Customer_IndividualEditDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krsné meno.
        /// </summary>
        public static string Customer_IndividualFirstName {
            get {
                return ResourceManager.GetString("Customer_IndividualFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID číslo.
        /// </summary>
        public static string Customer_IndividualID {
            get {
                return ResourceManager.GetString("Customer_IndividualID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priezvisko.
        /// </summary>
        public static string Customer_IndividualLastName {
            get {
                return ResourceManager.GetString("Customer_IndividualLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIČ.
        /// </summary>
        public static string Customer_IndividualTAXID {
            get {
                return ResourceManager.GetString("Customer_IndividualTAXID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titul.
        /// </summary>
        public static string Customer_IndividualTitle {
            get {
                return ResourceManager.GetString("Customer_IndividualTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IČ DPH.
        /// </summary>
        public static string Customer_IndividualVATID {
            get {
                return ResourceManager.GetString("Customer_IndividualVATID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO - Právnická osoba.
        /// </summary>
        public static string CustomerTab_Company {
            get {
                return ResourceManager.GetString("CustomerTab_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoznam.
        /// </summary>
        public static string CustomerTab_Company_PageSubtitle {
            get {
                return ResourceManager.GetString("CustomerTab_Company_PageSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO - Právnická osoba.
        /// </summary>
        public static string CustomerTab_Company_PageTitle {
            get {
                return ResourceManager.GetString("CustomerTab_Company_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FO - Fyzická osoba.
        /// </summary>
        public static string CustomerTab_Individual {
            get {
                return ResourceManager.GetString("CustomerTab_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoznam.
        /// </summary>
        public static string CustomerTab_Individual_PageSubtitle {
            get {
                return ResourceManager.GetString("CustomerTab_Individual_PageSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FO - Fyzická osoba.
        /// </summary>
        public static string CustomerTab_Individual_PageTitle {
            get {
                return ResourceManager.GetString("CustomerTab_Individual_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denný sumár .
        /// </summary>
        public static string DailyDataTab {
            get {
                return ResourceManager.GetString("DailyDataTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckSum.
        /// </summary>
        public static string File_CheckSum {
            get {
                return ResourceManager.GetString("File_CheckSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čas vytvorenia.
        /// </summary>
        public static string File_CreationTime {
            get {
                return ResourceManager.GetString("File_CreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Názov súboru.
        /// </summary>
        public static string File_Name {
            get {
                return ResourceManager.GetString("File_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis stránky.
        /// </summary>
        public static string FileDuplicity_PageSubtitle {
            get {
                return ResourceManager.GetString("FileDuplicity_PageSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicitné súbory.
        /// </summary>
        public static string FileDuplicity_PageTitle {
            get {
                return ResourceManager.GetString("FileDuplicity_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicitné súbory.
        /// </summary>
        public static string FileDuplicity_TableTitle {
            get {
                return ResourceManager.GetString("FileDuplicity_TableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis stránky.
        /// </summary>
        public static string FileInfo_PageSubtitle {
            get {
                return ResourceManager.GetString("FileInfo_PageSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vstupné súbory.
        /// </summary>
        public static string FileInfo_PageTitle {
            get {
                return ResourceManager.GetString("FileInfo_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vstupné súbory.
        /// </summary>
        public static string FileInfo_TableTitle {
            get {
                return ResourceManager.GetString("FileInfo_TableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyhodnotenie Odobratých Služieb Katastra.
        /// </summary>
        public static string Home_SubTitle {
            get {
                return ResourceManager.GetString("Home_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOSK.
        /// </summary>
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fakturácie.
        /// </summary>
        public static string Menu_Fakturacie {
            get {
                return ResourceManager.GetString("Menu_Fakturacie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moje fakturačné údaje.
        /// </summary>
        public static string Menu_FakturacneData {
            get {
                return ResourceManager.GetString("Menu_FakturacneData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametre systému.
        /// </summary>
        public static string Menu_GeneralSetup {
            get {
                return ResourceManager.GetString("Menu_GeneralSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavenia.
        /// </summary>
        public static string Menu_Nastavenia {
            get {
                return ResourceManager.GetString("Menu_Nastavenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Používatelia.
        /// </summary>
        public static string Menu_Pouzivatelia {
            get {
                return ResourceManager.GetString("Menu_Pouzivatelia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prehľad.
        /// </summary>
        public static string Menu_Prehlad {
            get {
                return ResourceManager.GetString("Menu_Prehlad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesy.
        /// </summary>
        public static string Menu_Procesy {
            get {
                return ResourceManager.GetString("Menu_Procesy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Menu_Report {
            get {
                return ResourceManager.GetString("Menu_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Služby.
        /// </summary>
        public static string Menu_Sluzby {
            get {
                return ResourceManager.GetString("Menu_Sluzby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zákazníci.
        /// </summary>
        public static string Menu_Zakaznici {
            get {
                return ResourceManager.GetString("Menu_Zakaznici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesačný sumár .
        /// </summary>
        public static string MonthlyDataTab {
            get {
                return ResourceManager.GetString("MonthlyDataTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popisné číslo.
        /// </summary>
        public static string OwnerAddressBuildingNumber {
            get {
                return ResourceManager.GetString("OwnerAddressBuildingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesto.
        /// </summary>
        public static string OwnerAddressCity {
            get {
                return ResourceManager.GetString("OwnerAddressCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krajina.
        /// </summary>
        public static string OwnerAddressCountry {
            get {
                return ResourceManager.GetString("OwnerAddressCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulica.
        /// </summary>
        public static string OwnerAddressStreet {
            get {
                return ResourceManager.GetString("OwnerAddressStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSČ.
        /// </summary>
        public static string OwnerAddressZipCode {
            get {
                return ResourceManager.GetString("OwnerAddressZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN.
        /// </summary>
        public static string OwnerBankAccountIban {
            get {
                return ResourceManager.GetString("OwnerBankAccountIban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IČO.
        /// </summary>
        public static string OwnerCompanyID {
            get {
                return ResourceManager.GetString("OwnerCompanyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spoločnosť.
        /// </summary>
        public static string OwnerCompanyName {
            get {
                return ResourceManager.GetString("OwnerCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIČ.
        /// </summary>
        public static string OwnerCompanyTAXID {
            get {
                return ResourceManager.GetString("OwnerCompanyTAXID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Právna forma.
        /// </summary>
        public static string OwnerCompanyType {
            get {
                return ResourceManager.GetString("OwnerCompanyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IČ DPH.
        /// </summary>
        public static string OwnerCompanyVATID {
            get {
                return ResourceManager.GetString("OwnerCompanyVATID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string OwnerContactEmail {
            get {
                return ResourceManager.GetString("OwnerContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobil.
        /// </summary>
        public static string OwnerContactMobile {
            get {
                return ResourceManager.GetString("OwnerContactMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefón.
        /// </summary>
        public static string OwnerContactPhone {
            get {
                return ResourceManager.GetString("OwnerContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string OwnerContactWeb {
            get {
                return ResourceManager.GetString("OwnerContactWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meno.
        /// </summary>
        public static string OwnerResponsibleFirstName {
            get {
                return ResourceManager.GetString("OwnerResponsibleFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priezvisko.
        /// </summary>
        public static string OwnerResponsiblelastName {
            get {
                return ResourceManager.GetString("OwnerResponsiblelastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stránka na správu vzorov - Patternov.
        /// </summary>
        public static string Patterns_PageSubtitle {
            get {
                return ResourceManager.GetString("Patterns_PageSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vzory.
        /// </summary>
        public static string Patterns_PageTitle {
            get {
                return ResourceManager.GetString("Patterns_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoznam vzorov.
        /// </summary>
        public static string Patterns_TableTitle {
            get {
                return ResourceManager.GetString("Patterns_TableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis stránky.
        /// </summary>
        public static string Process_PageSubtitle {
            get {
                return ResourceManager.GetString("Process_PageSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesy.
        /// </summary>
        public static string Process_PageTitle {
            get {
                return ResourceManager.GetString("Process_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesy.
        /// </summary>
        public static string Process_TableTitle {
            get {
                return ResourceManager.GetString("Process_TableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vstupné súbory.
        /// </summary>
        public static string ProcessTab_File {
            get {
                return ResourceManager.GetString("ProcessTab_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicitné súbory.
        /// </summary>
        public static string ProcessTab_FileDuplicity {
            get {
                return ResourceManager.GetString("ProcessTab_FileDuplicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stav procesov.
        /// </summary>
        public static string ProcessTab_Status {
            get {
                return ResourceManager.GetString("ProcessTab_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapamätať?.
        /// </summary>
        public static string Remember {
            get {
                return ResourceManager.GetString("Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktívne.
        /// </summary>
        public static string Service_Active {
            get {
                return ResourceManager.GetString("Service_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Základná cena.
        /// </summary>
        public static string Service_BasicPrice {
            get {
                return ResourceManager.GetString("Service_BasicPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kód.
        /// </summary>
        public static string Service_Code {
            get {
                return ResourceManager.GetString("Service_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        public static string Service_Description {
            get {
                return ResourceManager.GetString("Service_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čas zápisu.
        /// </summary>
        public static string Service_InsertTime {
            get {
                return ResourceManager.GetString("Service_InsertTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posledná zmena.
        /// </summary>
        public static string Service_LastUpdate {
            get {
                return ResourceManager.GetString("Service_LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stránka na správu servisov.
        /// </summary>
        public static string Service_PageSubtitle {
            get {
                return ResourceManager.GetString("Service_PageSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servisy.
        /// </summary>
        public static string Service_PageTitle {
            get {
                return ResourceManager.GetString("Service_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vzory.
        /// </summary>
        public static string Service_Patterns {
            get {
                return ResourceManager.GetString("Service_Patterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoznam servisov.
        /// </summary>
        public static string Service_TableTitle {
            get {
                return ResourceManager.GetString("Service_TableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoznam oprávnených používateľov.
        /// </summary>
        public static string UserList_PageSubtitle_ {
            get {
                return ResourceManager.GetString("UserList_PageSubtitle_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Používatelia.
        /// </summary>
        public static string UserList_PageTitle_ {
            get {
                return ResourceManager.GetString("UserList_PageTitle_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Používatelia.
        /// </summary>
        public static string UserList_TableTitle_ {
            get {
                return ResourceManager.GetString("UserList_TableTitle_", resourceCulture);
            }
        }
    }
}
