//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_LogService
    {
        public long batchID { get; set; }
        public long fileID { get; set; }
        public System.DateTime insertDateTime { get; set; }
        public string customerID { get; set; }
        public Nullable<int> serviceID { get; set; }
        public string col1 { get; set; }
        public string col2 { get; set; }
        public string col3 { get; set; }
        public string col4 { get; set; }
        public string col5 { get; set; }
        public string col6 { get; set; }
        public string col7 { get; set; }
        public string col8 { get; set; }
        public string col9 { get; set; }
    }
}
