//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_Service
    {
        public int serviceID { get; set; }
        public string Identifier { get; set; }
        public string Description { get; set; }
        public Nullable<int> userID { get; set; }
        public System.DateTime insertDateTime { get; set; }
    }
}
