//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stage_LogImport
    {
        public long batchID { get; set; }
        public string originalFileName { get; set; }
        public string originalCheckSum { get; set; }
        public string preProcessFileName { get; set; }
        public string Node_IP_Address { get; set; }
        public string UserID { get; set; }
        public string Date_Of_Request { get; set; }
        public string Requested_URL { get; set; }
        public string Request_Status { get; set; }
        public string Bytes_Sent { get; set; }
        public string Request_Time { get; set; }
        public string Unknown { get; set; }
        public string User_Agent { get; set; }
        public string User_IP_Address { get; set; }
    }
}
