// <auto-generated />
namespace WebPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20170906_init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20170906_init));
        
        string IMigrationMetadata.Id
        {
            get { return "201706092019436_2017-09-06_init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
