USE log4service
GO

DELETE FROM [CATServicePatterns]; --Foreign key
DBCC CHECKIDENT ('CATServicePatterns', RESEED, 0);
DELETE FROM [CATServiceParameters];

-- Insert service A 2.1.2
INSERT INTO [dbo].[CATServiceParameters]([PKServiceID],[ServiceCode],[ServiceDescription],[ServiceBasicPrice]) VALUES(2,'2.1.2',N'A.2.1.2 - Poskytnutie priestorovej informácie zo súboru geodetických informácií z KN',0.001)
-- Insert pattern
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/kn_wfs/MapServer/WFSServer%',null, '2.1.2', 2, 'MINV', N'Katastrálna mapa WFS', N'S-JTSK');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/kn_wms_norm/MapServer/WMSServer%',null, '2.1.2', 2, null, N'Katastrálna mapa WMS' ,N'WebMercator + S-JTSK');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/kn_wms_orto/MapServer/WMSServer%',null, '2.1.2', 2, null, N'Katastrálna mapa WMS - inverzná' ,N'WebMercator + S-JTSK');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/kn_wmts_norm_sjtsk/MapServer/WMTS/1.0.0/WMTSCapabilities.xml%',null, '2.1.2', 2, null, N'Katastrálna mapa WMTS' ,N'S-JTSK');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/kn_wmts_norm_wm/MapServer/WMTS/1.0.0/WMTSCapabilities.xml%',null, '2.1.2', 2, null, N'Katastrálna mapa WMTS' ,N'WebMercator');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/kn_wmts_orto_sjtsk/MapServer/WMTS/1.0.0/WMTSCapabilities.xml%',null, '2.1.2', 2, null, N'Katastrálna mapa WMTS - inverzná' ,N'S-JTSK');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/kn_wmts_orto_wm/MapServer/WMTS/1.0.0/WMTSCapabilities.xml%',null, '2.1.2', 2, null, N'Katastrálna mapa WMTS - inverzná' ,N'WebMercator');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/uo_wfs/MapServer/WFSServer%',null, '2.1.2', 2, 'MINV', N'Mapa určeného operátu WFS' ,N'S-JTSK');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/uo_wms_norm/MapServer/WMSServer%',null, '2.1.2', 2, null, N'Mapa určeného operátu WMS' ,N'WebMercator + S-JTSK');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/uo_wms_orto/MapServer/WMSServer%',null, '2.1.2', 2, null, N'Mapa určeného operátu WMS - inverzná' ,N'WebMercator + S-JTSK');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/uo_wmts_norm_sjtsk/MapServer/WMTS/1.0.0/WMTSCapabilities.xml%',null, '2.1.2', 2, null, N'Mapa určeného operátu WMTS' ,N'S-JTSK');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/uo_wmts_norm_wm/MapServer/WMTS/1.0.0/WMTSCapabilities.xml%',null, '2.1.2', 2, null, N'Mapa určeného operátu WMTS' ,N'WebMercator');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/uo_wmts_orto_sjtsk/MapServer/WMTS/1.0.0/WMTSCapabilities.xml%',null, '2.1.2', 2, null, N'Mapa určeného operátu WMTS - inverzná' ,N'S-JTSK');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/uo_wmts_orto_wm/MapServer/WMTS/1.0.0/WMTSCapabilities.xml%',null, '2.1.2', 2, null, N'Mapa určeného operátu WMTS - inverzná' ,N'WebMercator');
-- Insert service A 2.1.3
INSERT INTO [dbo].[CATServiceParameters]([PKServiceID],[ServiceCode],[ServiceDescription],[ServiceBasicPrice]) VALUES(3,'2.1.3',N'A.2.1.3 - Poskytnutie informácie z KN o vlastníkoch a iných oprávnených osobách',0.001);
-- Insert pattern
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Subjects?$select=Id&$filter=IdNo%',null,'2.1.3',3,null,N'Fyzická / Právnická osoba (FOPO)',N'IČO právnickej osoby');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Subjects(%)%',null,'2.1.3',3,null,N'Fyzická / Právnická osoba (FOPO)',N'Interné ID FOPO');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Kn.Search%',null,'2.1.3',3,null,N'Fyzická / Právnická osoba (FOPO)',N'Meno + priezvisko + rodné číslo fyzickej osoby');
-- Insert service A 2.1.4
INSERT INTO [dbo].[CATServiceParameters]([PKServiceID],[ServiceCode],[ServiceDescription],[ServiceBasicPrice]) VALUES(4,'2.1.4',N'A.2.1.4 - Poskytnutie informácie z KN o nehnuteľnostiach',0.001);
-- Insert pattern
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Spaces(%)?$select=%',null,'2.1.4',4,null,N'Bytové a nebytové priestory',N'Interné ID priestoru');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Spaces/?&$filter=CadastralUnit/Code %Construction/Folio/No %',null,'2.1.4',4,null,N'Bytové a nebytové priestory',N'Kód k.ú. + číslo listu vlastníctva');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Spaces/?&$filter=Entrance/HouseNo %CadastralUnit/Code %',null,'2.1.4',4,null,N'Bytové a nebytové priestory',N'Kód k.ú. + súpisné číslo');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Spaces/?&$filter=Entrance/HouseNo %CadastralUnit/Code %NonresidentialNo %',null,'2.1.4',4,null,N'Bytové a nebytové priestory',N'Kód k.ú. + súpisné číslo + číslo nebytového priestoru');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Spaces/?&$filter=Entrance/HouseNo %CadastralUnit/Code %FlatNo %',null,'2.1.4',4,null,N'Bytové a nebytové priestory',N'Kód k.ú. + súpisné číslo + číslo bytu');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Spaces/?&$filter=Municipality/Code %Construction/Folio/No %' ,null,'2.1.4',4,null,N'Bytové a nebytové priestory',N'Kód obce + číslo listu vlastníctva');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Spaces/?&$filter=Municipality/Code %Entrance/HouseNo %' ,null,'2.1.4',4,null,N'Bytové a nebytové priestory',N'Kód obce + súpisné číslo');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Spaces/?&$filter=Municipality/Code %Entrance/HouseNo  %NonresidentialNo %' ,null,'2.1.4',4,null,N'Bytové a nebytové priestory',N'Kód obce + súpisné číslo + číslo nebytového priestoru');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Spaces/?&$filter=Municipality/Code %Entrance/HouseNo  %FlatNo %' ,null,'2.1.4',4,null,N'Bytové a nebytové priestory',N'Kód obce + súpisné číslo + číslo bytu');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/ParcelsC(%)?$select=%',null,'2.1.4',4,null,N'Parcely C',N'Interné ID parcely registra C');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/ParcelsC/?&$filter=CadastralUnit/Code %Folio/No %',null,'2.1.4',4,null,N'Parcely C',N'Kód k.ú. + číslo listu vlastníctva');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/ParcelsC/?&$filter=CadastralUnit/Code %No %',null,'2.1.4',4,null,N'Parcely C',N'Kód k.ú. + číslo parcely registra C');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/ParcelsC/?&$filter=Municipality/Code %Folio/No %',null,'2.1.4',4,null,N'Parcely C',N'Kód obce + číslo listu vlastníctva');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/ParcelsC/?&$filter=Municipality/Code %No %',null,'2.1.4',4,null,N'Parcely C',N'Kód obce + číslo parcely registra C');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/ParcelsÈ(%)?$select=%',null,'2.1.4',4,null,N'Parcely E',N'Interné ID parcely registra C');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/ParcelsE/?&$filter=CadastralUnit/Code %Folio/No %',null,'2.1.4',4,null,N'Parcely E',N'Kód k.ú. + číslo listu vlastníctva');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/ParcelsE/?&$filter=CadastralUnit/Code %No %',null,'2.1.4',4,null,N'Parcely E',N'Kód k.ú. + číslo parcely registra E');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/ParcelsE/?&$filter=Municipality/Code %Folio/No %',null,'2.1.4',4,null,N'Parcely E',N'Kód obce + číslo listu vlastníctva');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/ParcelsE/?&$filter=Municipality/Code %No %',null,'2.1.4',4,null,N'Parcely E',N'Kód obce + číslo parcely registra E');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Constructions(%)?$select=%',null,'2.1.4',4,null,N'Stavby',N'Interné ID stavby');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Constructions/?&$filter=CadastralUnit/Code %Folio/No %',null,'2.1.4',4,null,N'Stavby',N'Kód k.ú. + číslo listu vlastníctva');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Constructions/?&$filter=CadastralUnit/Code %ParcelsC/any(%',null,'2.1.4',4,null,N'Stavby',N'Kód k.ú. + číslo parcely registra C');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Constructions/?&$filter=CadastralUnit/Code %HouseNo %',null,'2.1.4',4,null,N'Stavby',N'Kód k.ú. + súpisné číslo');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Constructions/?&$filter=Municipality/Code/Code %Folio/No %',null,'2.1.4',4,null,N'Stavby',N'Kód obce + číslo listu vlastníctva');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Constructions/?&$filter=Municipality/Code/Code %ParcelsC/any(%',null,'2.1.4',4,null,N'Stavby',N'Kód obce + číslo parcely registra C');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Constructions/?&$filter=Municipality/Code/Code %HouseNo %',null,'2.1.4',4,null,N'Stavby',N'Kód obce + súpisné číslo');

-- Insert service A 2.1.5
INSERT INTO [dbo].[CATServiceParameters]([PKServiceID],[ServiceCode],[ServiceDescription],[ServiceBasicPrice]) VALUES(5,'2.1.5',N'A.2.1.5 Poskytnutie informácie z KN o právach k nehnuteľnostiam',0.001);
-- Insert pattern
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Participants(%)/?&$select=%',null,'2.1.14',5,null  ,N'Účastník právneho vzťahu (účastník)',N'Interné ID účastníka');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Folios(%)/ParcelsC%',null,'2.1.5',5,null  ,N'Účastník právneho vzťahu (účastník)',N'Interné ID účastníka');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Folios(%)/ParcelsE%',null,'2.1.5',5,null  ,N'Účastník právneho vzťahu (účastník)',N'Interné ID účastníka');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Folios(%)/Constructions%',null,'2.1.5',5,null  ,N'Účastník právneho vzťahu (účastník)',N'Interné ID účastníka');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Folios(%)/SpaceRecords%',null,'2.1.5',5,null  ,N'Účastník právneho vzťahu (účastník)',N'Interné ID účastníka');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Folios(%)/LegalRightRecords%',null,'2.1.5',5,null  ,N'Účastník právneho vzťahu (účastník)',N'Interné ID účastníka');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Participants/?$filter=CadastralUnit/Code eq % and OwnershipRecord/Folio/ParcelsC/any(%',null,'2.1.5',5,null  ,N'Účastník právneho vzťahu (účastník)',N'Kód k.ú. + číslo parcely registra C');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Participants/?$filter=CadastralUnit/Code eq % and OwnershipRecord/Folio/ParcelsE/any(%',null,'2.1.5',5,null  ,N'Účastník právneho vzťahu (účastník)',N'Kód k.ú. + číslo parcely registra E');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Participants/?$filter=CadastralUnit/Code eq % and Subjects/any(%',null,'2.1.5',5,null  ,N'Účastník právneho vzťahu (účastník)',N'Kód k.ú. + interné ID FOPO');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Participants/?$filter=CadastralUnit/Code eq % and OwnershipRecord/Folio/Constructions/any(p: p/HouseNo eq %)&$select%',null,'2.1.5',5,null  ,N'Účastník právneho vzťahu (účastník)',N'Kód k.ú. + súpisné číslo stavby');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Participants/?$filter=CadastralUnit/Code eq % and OwnershipRecord/Folio/Constructions/any(p: p/HouseNo eq %) and OwnershipRecord/SpaceRecords/any(%p/Space/FlatNo%',null,'2.1.5',5,null  ,N'Účastník právneho vzťahu (účastník)',N'Kód k.ú. + súpisné číslo stavby + číslo bytu');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Participants/?$filter=CadastralUnit/Code eq % and OwnershipRecord/Folio/Constructions/any(p: p/HouseNo eq %) and OwnershipRecord/SpaceRecords/any(%p/Space/NonresidentialNo%',null,'2.1.5',5,null  ,N'Účastník právneho vzťahu (účastník)',N'Kód k.ú. + súpisné číslo stavby + číslo nebytového priestoru');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Participants/?$filter=CadastralUnit/Code eq % and OwnershipRecord/Folio/ParcelsE/any(%',null,'2.1.5',5,null  ,N'Účastník právneho vzťahu (účastník)',N'Kód k.ú. +  číslo pôvodného k.ú. + číslo parcely registra E');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Folios(%)/?&$select=Id,ValidTo,No&$expand=CadastralUnit%',null,'2.1.5',5,null  ,N'Zoznam právnych vzťahov na LV nepriradených k účastníkovi',N'Interné ID listu vlastníctva');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/OwnershipRecords(%)/LegalRightRecords%',null,'2.1.5',5,null  ,N'Zoznam právnych vzťahov na LV nepriradených k účastníkovi',N'Interné ID listu vlastníctva');
-- Insert service A 2.1.6
INSERT INTO [dbo].[CATServiceParameters]([PKServiceID],[ServiceCode],[ServiceDescription],[ServiceBasicPrice]) VALUES(6,'2.1.6',N'A.2.1.6 Poskytnutie informácie z KN o registri územno technických jednotiek',0.001);
-- Insert pattern
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/CadastralUnits?$filter=Id eq%&$select%',null,'2.1.6',6,null  ,N'Register katastrálnych území',N'Interné ID k.ú.');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/CadastralUnits?$filter=Code eq%&$select%',null,'2.1.6',6,null  ,N'Register katastrálnych území',N'Kód k.ú.');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/CadastralUnits?$filter=Municipality/Code eq%&$select%',null,'2.1.6',6,null  ,N'Register katastrálnych území',N'Kód obce');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/CadastralUnits?$filter=Name eq%&$select=%',null,'2.1.6',6,null  ,N'Register katastrálnych území',N'Názov k.ú.');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/CadastralUnits?&$select%',null,'2.1.6',6,null  ,N'Register katastrálnych území',N'Všetky k.ú.');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Regions?$filter=Id eq%&$select%',null,'2.1.6',6,null  ,N'Register krajov',N'Interné ID kraja');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Regions?$filter=Code eq%&$select%',null,'2.1.6',6,null  ,N'Register krajov',N'Kód kraja');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Regions?$filter=Name eq%&$select%',null,'2.1.6',6,null  ,N'Register krajov',N'Názov kraja');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Regions?&$select%',null,'2.1.6',6,null  ,N'Register krajov',N'Všetky kraje');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Municipalities?$filter=Id eq%&$select%',null,'2.1.6',6,null  ,N'Register obcí',N'Interné ID obce');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Municipalities?$filter=Code eq%&$select%',null,'2.1.6',6,null  ,N'Register obcí',N'Kód obce');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Municipalities?$filter=District/Code eq%&$select%',null,'2.1.6',6,null  ,N'Register obcí',N'Kód okresu');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Municipalities?$filter=Name eq%&$select%',null,'2.1.6',6,null  ,N'Register obcí',N'Názov obce');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Municipalities?&$select%',null,'2.1.6',6,null  ,N'Register obcí',N'Všetky obce');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Districts?$filter=Id eq%&$select%',null,'2.1.6',6,null  ,N'Register okresov',N'Interné ID okresu');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Districts?$filter=Region/Code eq%>&$select%',null,'2.1.6',6,null  ,N'Register okresov',N'Kód kraja');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Districts?$filter=Code eq%&$select%',null,'2.1.6',6,null  ,N'Register okresov',N'Kód okresu');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Districts?$filter=Name eq%&$select%',null,'2.1.6',6,null  ,N'Register okresov',N'Názov okresu');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Districts?&$select%',null,'2.1.6',6,null  ,N'Register okresov',N'Všetky okresy');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/OriginalCadastralUnits?$filter=Id eq%&$select%',null,'2.1.6',6,null  ,N'Register pôvodných katastrálnych území',N'Interné ID pôvodného k.ú.');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/OriginalCadastralUnits?$filter=CadastralUnit/Code eq%and Id gt 0&$select%',null,'2.1.6',6,null  ,N'Register pôvodných katastrálnych území',N'Kód k.ú.');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/OriginalCadastralUnits?$filter=Id gt 0&$select%',null,'2.1.6',6,null  ,N'Register pôvodných katastrálnych území',N'Všetky pôvodné k.ú.');

-- Insert service A 2.1.7
INSERT INTO [dbo].[CATServiceParameters]([PKServiceID],[ServiceCode],[ServiceDescription],[ServiceBasicPrice]) VALUES(7,'2.1.7',N'A.2.1.7 Poskytnutie informácie z KN o číselníkoch',0.001);
-- Insert pattern
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/ProtectedProperties?$filter=Id gt 0&$select%',null,'2.1.7',7,null  ,N'Druh chránenej nehnuteľnosti',N'Všetky hodnoty');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/NonresidentialSpaceTypes?$filter=Id gt 0&$select%',null,'2.1.7',7,null  ,N'Druh nebytového priestoru',N'Všetky hodnoty');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/LandUses?$filter=Id gt 0&$select%',null,'2.1.7',7,null  ,N'Druh pozemku',N'Všetky hodnoty');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/OwnershipTypes?$filter=Id gt 0&$select%',null,'2.1.7',7,null  ,N'Druh právneho vzťahu',N'Všetky hodnoty');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/SpaceTypes?$filter=Id gt 0&$select%',null,'2.1.7',7,null  ,N'Druh priestoru',N'Všetky hodnoty');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/ConstructionTypes?$filter=Id gt 0&$select%',null,'2.1.7',7,null  ,N'Druh stavby',N'Všetky hodnoty');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Affiliations?$filter=Id gt 0&$select%',null,'2.1.7',7,null  ,N'Príslušnosť k PPF alebo LPF',N'Všetky hodnoty');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/SharedProperties?$filter=Id gt 0&$select%',null,'2.1.7',7,null  ,N'Spoločná nehnuteľnosť',N'Všetky hodnoty');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Utilisations?$filter=Id gt 0&$select%',null,'2.1.7',7,null  ,N'Spôsob využívania pozemku',N'Všetky hodnoty');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/OwnerTypes?$filter=Id gt 0&$select%',null,'2.1.7',7,null  ,N'Typ vlastníka',N'Všetky hodnoty');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/FolioPartTypes?$filter=Id gt 0&$select%',null,'2.1.7',7,null  ,N'Typy vpisov na liste vlastníctva',N'Všetky hodnoty');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/ParticipantTypes?$filter=Id gt 0&$select%',null,'2.1.7',7,null  ,N'Účastník právneho vzťahu',N'Všetky hodnoty');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Localizations?$filter=Id gt 0&$select%',null,'2.1.7',7,null  ,N'Umiestnenie pozemku',N'Všetky hodnoty');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/ConstructionLocalizations?$filter=Id gt 0&$select%',null,'2.1.7',7,null  ,N'Umiestnenie stavby',N'Všetky hodnoty');

-- Insert service A 2.1.9
INSERT INTO [dbo].[CATServiceParameters]([PKServiceID],[ServiceCode],[ServiceDescription],[ServiceBasicPrice]) VALUES(9,'2.1.9',N'A.2.1.9 Poskytnutie výpisu z listu vlastníctva z KN',0.001);
-- Insert pattern
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Folios/?$filter=Id eq %&$select%',null,'2.1.9',9,null  ,N'Hlavička výpisu z listu vlastníctva',N'Interné ID listu vlastníctva');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Folios/?$filter=CadastralUnit/Code eq % and No eq %&$select%',null,'2.1.9',9,null  ,N'Hlavička výpisu z listu vlastníctva',N'Kód k.ú. + číslo listu vlastníctva');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Folios?$filter=Constructions/any(d:d/HouseNo eq %) and CadastralUnit/Code eq %&$select%',null,'2.1.9',9,null  ,N'Hlavička výpisu z listu vlastníctva',N'Kód k.ú. + súpisné číslo');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Folios?$filter=ParcelsC/any(d:d/No eq %) and CadastralUnit/Code eq %&$select%',null,'2.1.9',9,null  ,N'Hlavička výpisu z listu vlastníctva',N'Kód k.ú. + číslo parcely registra C');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Folios?$filter=ParcelsE/any(d:d/No eq %) and CadastralUnit/Code eq %&$select%',null,'2.1.9',9,null  ,N'Hlavička výpisu z listu vlastníctva',N'Kód k.ú. + číslo parcely registra E');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/GeneratePrf?prfId=%&outputType=html%',null,'2.1.9',9,null  ,N'Vizualizácia výpisu z listu vlastníctva - html',N'Interné ID listu vlastníctva');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/GeneratePrf?prfNumber=%&cadastralUnitCode=%&outputType=html%',null,'2.1.9',9,null  ,N'Vizualizácia výpisu z listu vlastníctva - html',N'Kód k.ú. + číslo listu vlastníctva');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/GeneratePrf?houseNo=%&cadastralUnitCode=%&outputType=html%',null,'2.1.9',9,null  ,N'Vizualizácia výpisu z listu vlastníctva - html',N'Kód k.ú. + súpisné číslo');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/GeneratePrf?parcelC=%&cadastralUnitCode=%&outputType=html%',null,'2.1.9',9,null  ,N'Vizualizácia výpisu z listu vlastníctva - html',N'Kód k.ú. + číslo parcely registra C');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/GeneratePrf?parcelE=%&cadastralUnitCode=%&outputType=html%',null,'2.1.9',9,null  ,N'Vizualizácia výpisu z listu vlastníctva - html',N'Kód k.ú. + číslo parcely registra E');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/GeneratePrf?prfId=%&outputType=pdf%',null,'2.1.9',9,null  ,N'Vizualizácia výpisu z listu vlastníctva - pdf',N'Interné ID listu vlastníctva');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/GeneratePrf?prfNumber=%&cadastralUnitCode=%&outputType=pdf%',null,'2.1.9',9,null  ,N'Vizualizácia výpisu z listu vlastníctva - pdf',N'Kód k.ú. + číslo listu vlastníctva');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/GeneratePrf?houseNo=%&cadastralUnitCode=%&outputType=pdf%',null,'2.1.9',9,null  ,N'Vizualizácia výpisu z listu vlastníctva - pdf',N'Kód k.ú. + súpisné číslo');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/GeneratePrf?parcelC=%&cadastralUnitCode=%&outputType=pdf%',null,'2.1.9',9,null  ,N'Vizualizácia výpisu z listu vlastníctva - pdf',N'Kód k.ú. + číslo parcely registra C');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/GeneratePrf?parcelE=%&cadastralUnitCode=%&outputType=pdf%',null,'2.1.9',9,null  ,N'Vizualizácia výpisu z listu vlastníctva - pdf',N'Kód k.ú. + číslo parcely registra E');

-- Insert service A 2.1.13
INSERT INTO [dbo].[CATServiceParameters]([PKServiceID],[ServiceCode],[ServiceDescription],[ServiceBasicPrice]) VALUES(13,'2.1.13',N'A.2.1.13 Poskytnutie informácie z KN o súpise parciel z registra C a E',0.001);
-- Insert pattern
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/ParcelsC/?&$filter=CadastralUnit/Code eq % and StatusId ne 3&$select%',null,'2.1.13',13,null  ,N'Súpis parciel registra C',N'Kód k.ú.');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/ParcelsC/?&$filter=Municipality/Code eq % and StatusId ne 3&$select%',null,'2.1.13',13,null  ,N'Súpis parciel registra C',N'Kód obce');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/ParcelsE/?&$filter=CadastralUnit/Code eq % and StatusId ne 3&$select=%',null,'2.1.13',13,null  ,N'Súpis parciel registra E',N'Kód k.ú.');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/ParcelsE/?&$filter=Municipality/Code eq % and StatusId ne 3&$select%',null,'2.1.13',13,null  ,N'Súpis parciel registra E',N'Kód obce');

-- Insert service A 2.1.14
INSERT INTO [dbo].[CATServiceParameters]([PKServiceID],[ServiceCode],[ServiceDescription],[ServiceBasicPrice]) VALUES(14,'2.1.14',N'A.2.1.14 - Poskytnutie informácie z KN o súpise stavieb',0.001);
-- Insert pattern
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Spaces/?&$filter=CadastralUnit/Code %select=Id%',null,'2.1.14',14,null  ,N'Súpis bytov a nebytových priestorov',N'Kód k.ú.');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Spaces/?&$filter=Municipality/Code %select=Id%',null,'2.1.14',14,null, N'Súpis bytov a nebytových priestorov',N'Kód obce');    
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Constructions/?&$filter=CadastralUnit/Code %select=Id%',null,'2.1.14',14,null, N'Súpis stavieb', N'Kód k.ú.');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Constructions/?&$filter=Municipality/Code %select=Id%',null,'2.1.14',14,null, N'Súpis stavieb', N'Kód obce');  

-- Insert service A 2.1.15
INSERT INTO [dbo].[CATServiceParameters]([PKServiceID],[ServiceCode],[ServiceDescription],[ServiceBasicPrice]) VALUES(15,'2.1.15',N'A.2.1.15 Poskytnutie informácie z KN o súpise vlastníkov',0.001);
-- Insert pattern
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Subjects?$filter=Participants/any(p: p/CadastralUnitId eq % and p/Type/Code eq 1)&$select%',null,'2.1.15',15,null  ,N'Súpis vlastníkov - FOPO',N'Interné ID k.ú.');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Subjects?$filter=Participants/any(p: p/CadastralUnit/Code eq % and p/Type/Code eq 1)&$select%',null,'2.1.15',15,null  ,N'Súpis vlastníkov - FOPO',N'Kód k.ú.');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Subjects?$filter=Participants/any(p: p/ Municipality/Code eq % and p/Type/Code eq 1)&$select%',null,'2.1.15',15,null  ,N'Súpis vlastníkov - FOPO',N'Kód obce');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/GetSubjects?cadastralUnitCode=%&participantType=1%',null,'2.1.15',15,null  ,N'Súpis vlastníkov - hash rodných čísiel',N'Kód k.ú.');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/GetSubjects?municipalityCode=%&participantType=1%',null,'2.1.15',15,null  ,N'Súpis vlastníkov - hash rodných čísiel',N'Kód obce');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Participants?$filter=Type/Code eq 1 and CadastralUnitId eq %&$select%',null,'2.1.15',15,null  ,N'Súpis vlastníkov - účastníci',N'Interné ID k.ú.');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Participants?$filter=Type/Code eq 1 and CadastralUnit/Code eq %&$select%',null,'2.1.15',15,null  ,N'Súpis vlastníkov - účastníci',N'Kód k.ú.');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Participants?$filter=Type/Code eq 1 and Municipality/Code eq %&$select%',null,'2.1.15',15,null  ,N'Súpis vlastníkov - účastníci',N'Kód obce');

-- Insert service A 2.1.16
INSERT INTO [dbo].[CATServiceParameters]([PKServiceID],[ServiceCode],[ServiceDescription],[ServiceBasicPrice]) VALUES(16,'2.1.16',N'A.2.1.16 Poskytnutie informácie z KN o súpise správcov',0.001);
-- Insert pattern
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Subjects?$filter=Participants/any(p: p/CadastralUnitId eq % and p/Type/Code eq 2)&$select%',null,'2.1.16',16,null  ,N'Súpis správcov - FOPO',N'Interné ID k.ú.');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Subjects?$filter=Participants/any(p: p/CadastralUnit/Code eq % and p/Type/Code eq 2)&$select%',null,'2.1.16',16,null  ,N'Súpis správcov - FOPO',N'Kód k.ú.');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Subjects?$filter=Participants/any(p: p/ Municipality/Code eq % and p/Type/Code eq 2)&$select%',null,'2.1.16',16,null  ,N'Súpis správcov - FOPO',N'Kód obce');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/GetSubjects?cadastralUnitCode=%&participantType=2%',null,'2.1.16',16,null  ,N'Súpis správcov - hash rodných čísiel',N'Kód k.ú.');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/GetSubjects?municipalityCode=%&participantType=2%',null,'2.1.16',16,null  ,N'Súpis správcov - hash rodných čísiel',N'Kód obce');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Participants?$filter=Type/Code eq 2 and CadastralUnitId eq %&$select%',null,'2.1.16',16,null  ,N'Súpis správcov - účastníci',N'Interné ID k.ú.');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Participants?$filter=Type/Code eq 2 and CadastralUnit/Code eq %&$select%',null,'2.1.16',16,null  ,N'Súpis správcov - účastníci',N'Kód k.ú.');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Participants?$filter=Type/Code eq 2 and Municipality/Code eq %&$select%',null,'2.1.16',16,null  ,N'Súpis správcov - účastníci',N'Kód obce');

-- Insert service A 2.1.17
INSERT INTO [dbo].[CATServiceParameters]([PKServiceID],[ServiceCode],[ServiceDescription],[ServiceBasicPrice]) VALUES(17,'2.1.17',N'A.2.1.17 Poskytnutie informácie z KN o súpise nájomcov',0.001);
-- Insert pattern
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Subjects?$filter=Participants/any(p: p/CadastralUnitId eq % and p/Type/Code eq 3)&$select%',null,'2.1.17',17,null  ,N'Súpis nájomcov - FOPO',N'Interné ID k.ú.');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Subjects?$filter=Participants/any(p: p/CadastralUnit/Code eq % and p/Type/Code eq 3)&$select%',null,'2.1.17',17,null  ,N'Súpis nájomcov - FOPO',N'Kód k.ú.');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Subjects?$filter=Participants/any(p: p/ Municipality/Code eq % and p/Type/Code eq 3)&$select%',null,'2.1.17',17,null  ,N'Súpis nájomcov - FOPO',N'Kód obce');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/GetSubjects?cadastralUnitCode=%&participantType=3%',null,'2.1.17',17,null  ,N'Súpis nájomcov - hash rodných čísiel',N'Kód k.ú.');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/GetSubjects?municipalityCode=%&participantType=3%',null,'2.1.17',17,null  ,N'Súpis nájomcov - hash rodných čísiel',N'Kód obce');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Participants?$filter=Type/Code eq 3 and CadastralUnitId eq %&$select%',null,'2.1.17',17,null  ,N'Súpis nájomcov - účastníci',N'Interné ID k.ú.');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Participants?$filter=Type/Code eq 3 and CadastralUnit/Code eq %&$select%',null,'2.1.17',17,null  ,N'Súpis nájomcov - účastníci',N'Kód k.ú.');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Participants?$filter=Type/Code eq 3 and Municipality/Code eq %&$select%',null,'2.1.17',17,null  ,N'Súpis nájomcov - účastníci',N'Kód obce');

-- Insert service A 2.1.18
INSERT INTO [dbo].[CATServiceParameters]([PKServiceID],[ServiceCode],[ServiceDescription],[ServiceBasicPrice]) VALUES(18,'2.1.18',N'A.2.1.18 Poskytnutie informácie z KN o súpise iných oprávnených osôb',0.001);
-- Insert pattern
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Subjects?$filter=Participants/any(p: p/CadastralUnitId eq % and p/Type/Code eq 4)&$select%',null,'2.1.18',18,null  ,N'Súpis iných oprávnených osôb - FOPO',N'Interné ID k.ú.');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Subjects?$filter=Participants/any(p: p/CadastralUnit/Code eq % and p/Type/Code eq 4)&$select%',null,'2.1.18',18,null  ,N'Súpis iných oprávnených osôb - FOPO',N'Kód k.ú.');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Subjects?$filter=Participants/any(p: p/ Municipality/Code eq % and p/Type/Code eq 4)&$select%',null,'2.1.18',18,null  ,N'Súpis iných oprávnených osôb - FOPO',N'Kód obce');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/GetSubjects?cadastralUnitCode=%&participantType=4%',null,'2.1.18',18,null  ,N'Súpis iných oprávnených osôb - hash rodných čísiel',N'Kód k.ú.');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/GetSubjects?municipalityCode=%&participantType=4%',null,'2.1.18',18,null  ,N'Súpis iných oprávnených osôb - hash rodných čísiel',N'Kód obce');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Participants?$filter=Type/Code eq 4 and CadastralUnitId eq %&$select%',null,'2.1.18',18,null  ,N'Súpis iných oprávnených osôb - účastníci',N'Interné ID k.ú.');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Participants?$filter=Type/Code eq 4 and CadastralUnit/Code eq %&$select%',null,'2.1.18',18,null  ,N'Súpis iných oprávnených osôb - účastníci',N'Kód k.ú.');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Participants?$filter=Type/Code eq 4 and Municipality/Code eq %&$select%',null,'2.1.18',18,null  ,N'Súpis iných oprávnených osôb - účastníci',N'Kód obce');

-- Insert service A 2.1.20
INSERT INTO [dbo].[CATServiceParameters]([PKServiceID],[ServiceCode],[ServiceDescription],[ServiceBasicPrice]) VALUES(20,'2.1.20',N'A.2.1.20 Poskytnutie informácie z KN na vybrané geodetické činnosti v KN',0.001);
-- Insert pattern
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/sk/Vgi/Download/%',null,'2.1.20',20,null  ,N'Mapy',N'ID mapy');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/ParcelMaps?$filter=CadastralUnit/Code eq %&$select%',null,'2.1.20',20,null  ,N'Zoznam máp vo formáte VGI',N'Kód k.ú.');


-- Insert service IOM
INSERT INTO [dbo].[CATServiceParameters]([PKServiceID],[ServiceCode],[ServiceDescription],[ServiceBasicPrice]) VALUES(30,'IOM',N'IOM DeliverRequest = Prijatie žiadosti Konzumenta  o výpis LV z LEGACY systému KN Poskytovateľa',0.001);
-- Insert pattern
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/soap%',null,'IOM',30,null  ,N'SOAP endpoint web service',N'soap');

--select * from CATServiceParameters;
--select p.ServiceDescription, t.* from CATServicePatterns t, CATServiceParameters p
--where p.PKServiceID = t.F KServiceID;