USE [log4service]
GO

/****** Object:  Index [IDX_DateTime]    Script Date: 25.9.2017 14:25:42 ******/
DROP INDEX [IDX_DateOfRequest] ON [dbo].[CATLogsOfService]
GO
CREATE NONCLUSTERED INDEX [IDX_DateOfRequest] ON [dbo].[CATLogsOfService]
(
	[DateOfRequest] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

DROP INDEX [IDX_DateOfRequest] ON [dbo].[CATCustomerDailyData]
GO
CREATE NONCLUSTERED INDEX [IDX_DateOfRequest] ON [dbo].[CATCustomerDailyData]
(
	[DateOfRequest] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

DROP INDEX [IDX_DateOfRequest] ON [dbo].[CATCustomerMonthlyData]
GO
CREATE NONCLUSTERED INDEX [IDX_DateOfRequest] ON [dbo].[CATCustomerMonthlyData]
(
	[DateOfRequest] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

DROP INDEX [IDX_DateOfRequest] ON [dbo].[CATInvoiceByDay]
GO
CREATE NONCLUSTERED INDEX [IDX_DateOfRequest] ON [dbo].[CATInvoiceByDay]
(
	[DateOfRequest] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

DROP INDEX [IDX_DateOfRequest] ON [dbo].[CATInvoiceByMonth]
GO
CREATE NONCLUSTERED INDEX [IDX_DateOfRequest] ON [dbo].[CATInvoiceByMonth]
(
	[DateOfRequest] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

DROP INDEX [IDX_StartBillingPeriod] ON [dbo].[CATSummaryInvoice]
GO
CREATE NONCLUSTERED INDEX [IDX_StartBillingPeriod] ON [dbo].[CATSummaryInvoice]
(
	[StartBillingPeriod] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO
