delete from [CATServicePatterns]; --Foreign key
DBCC CHECKIDENT ('CATServicePatterns', RESEED, 0);

delete from [CATServiceParameters];
DBCC CHECKIDENT ('CATServiceParameters', RESEED, 0);

-- Insert service A 2.1.02
INSERT INTO [dbo].[CATServiceParameters]([ServiceCode],[ServiceDescription],[ServiceBasicPrice]) VALUES('2.1.2',N'A.2.1.2 Poskytnutie priestorovej informácie zo súboru geodetických informácií z KN',0.001)
-- Insert pattern
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp1],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/kn_wfs/MapServer/WFSServer%',null,null,null,null,null,null, '2.1.2', 1, 'MINV', N'Katastrálna mapa WFS', N'S-JTSK');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp1],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/kn_wms_norm/MapServer/WMSServer%',null,null,null,null,null,null, '2.1.2', 1, null, N'Katastrálna mapa WMS' ,N'WebMercator + S-JTSK');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp1],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/kn_wms_orto/MapServer/WMSServer%',null,null,null,null,null,null, '2.1.2', 1, null, N'Katastrálna mapa WMS - inverzná' ,N'WebMercator + S-JTSK');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp1],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/kn_wmts_norm_sjtsk/MapServer/WMTS/1.0.0/WMTSCapabilities.xml%',null,null,null,null,null,null, '2.1.2', 1, null, N'Katastrálna mapa WMTS' ,N'S-JTSK');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp1],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/kn_wmts_norm_wm/MapServer/WMTS/1.0.0/WMTSCapabilities.xml%',null,null,null,null,null,null, '2.1.2', 1, null, N'Katastrálna mapa WMTS' ,N'WebMercator');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp1],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/kn_wmts_orto_sjtsk/MapServer/WMTS/1.0.0/WMTSCapabilities.xml%',null,null,null,null,null,null, '2.1.2', 1, null, N'Katastrálna mapa WMTS - inverzná' ,N'S-JTSK');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp1],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/kn_wmts_orto_wm/MapServer/WMTS/1.0.0/WMTSCapabilities.xml%',null,null,null,null,null,null, '2.1.2', 1, null, N'Katastrálna mapa WMTS - inverzná' ,N'WebMercator');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp1],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/uo_wfs/MapServer/WFSServer%',null,null,null,null,null,null, '2.1.2', 1, 'MINV', N'Mapa určeného operátu WFS' ,N'S-JTSK');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp1],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/uo_wms_norm/MapServer/WMSServer%',null,null,null,null,null,null, '2.1.2', 1, null, N'Mapa určeného operátu WMS' ,N'WebMercator + S-JTSK');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp1],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/uo_wms_orto/MapServer/WMSServer%',null,null,null,null,null,null, '2.1.2', 1, null, N'Mapa určeného operátu WMS - inverzná' ,N'WebMercator + S-JTSK');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp1],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/uo_wmts_norm_sjtsk/MapServer/WMTS/1.0.0/WMTSCapabilities.xml%',null,null,null,null,null,null, '2.1.2', 1, null, N'Mapa určeného operátu WMTS' ,N'S-JTSK');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp1],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/uo_wmts_norm_wm/MapServer/WMTS/1.0.0/WMTSCapabilities.xml%',null,null,null,null,null,null, '2.1.2', 1, null, N'Mapa určeného operátu WMTS' ,N'WebMercator');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp1],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/uo_wmts_orto_sjtsk/MapServer/WMTS/1.0.0/WMTSCapabilities.xml%',null,null,null,null,null,null, '2.1.2', 1, null, N'Mapa určeného operátu WMTS - inverzná' ,N'S-JTSK');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[PatternRegExp1],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/uo_wmts_orto_wm/MapServer/WMTS/1.0.0/WMTSCapabilities.xml%',null,null,null,null,null,null, '2.1.2', 1, null, N'Mapa určeného operátu WMTS - inverzná' ,N'WebMercator');
-- Insert service A 2.1.03
INSERT INTO [dbo].[CATServiceParameters]([ServiceCode],[ServiceDescription],[ServiceBasicPrice]) VALUES('2.1.3',N'A.2.1.03 Poskytnutie informácie z KN o vlastníkoch a iných oprávnených osobách',0.001);
-- Insert pattern
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Subjects?$select=Id&$filter=IdNo%',null,null,null,null,null,null,'2.1.3',null,N'Fyzická / Právnická osoba (FOPO)',N'IČO právnickej osoby');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Subjects(%)%',null,'2.1.3',null,null,null,null,null,null,N'Fyzická / Právnická osoba (FOPO)',N'Interné ID FOPO');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Kn.Search%',null,null,null,null,null,null,'2.1.3',null,N'Fyzická / Právnická osoba (FOPO)',N'Meno + priezvisko + rodné číslo fyzickej osoby');
-- Insert service A 2.1.04
INSERT INTO [dbo].[CATServiceParameters]([ServiceCode],[ServiceDescription],[ServiceBasicPrice]) VALUES('2.1.4',N'A.2.1.04 Poskytnutie informácie z KN o nehnuteľnostiach',0.001);
-- Insert pattern
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Spaces(%)?_24select=%',null,null,null,null,null,null,'2.1.4',null,N'Bytové a nebytové priestory',N'Interné ID priestoru');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Spaces/?&$filter=CadastralUnit/Code%20eq%Construction/Folio/No%20eq%',null,null,null,null,null,null,'2.1.4',null,N'Bytové a nebytové priestory',N'Kód k.ú. + číslo listu vlastníctva');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Spaces/?&$filter=Entrance/HouseNo%20eq%CadastralUnit/Code%20eq%',null,null,null,null,null,null,'2.1.4',null,N'Bytové a nebytové priestory',N'Kód k.ú. + súpisné číslo');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Spaces/?&$filter=Entrance/HouseNo%20eq%CadastralUnit/Code%20eq%NonresidentialNo%20eq%',null,null,null,null,null,null,'2.1.4',null,N'Bytové a nebytové priestory',N'Kód k.ú. + súpisné číslo + číslo nebytového priestoru');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Spaces/?&$filter=Entrance/HouseNo%20eq%CadastralUnit/Code%20eq%FlatNo%20eq%',null,null,null,null,null,null,'2.1.4',null,N'Bytové a nebytové priestory',N'Kód k.ú. + súpisné číslo + číslo bytu');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Spaces/?&$filter=Municipality/Code%20eq%Construction/Folio/No%20eq%' ,null,null,null,null,null,null,'2.1.4',null,N'Bytové a nebytové priestory',N'Kód obce + číslo listu vlastníctva');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Spaces/?&$filter=Municipality/Code%20eq%Entrance/HouseNo%20eq%' ,null,null,null,null,null,null,'2.1.4',null,N'Bytové a nebytové priestory',N'Kód obce + súpisné číslo');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Spaces/?&$filter=Municipality/Code%20eq%Entrance/HouseNo%20eq%20eq%NonresidentialNo%20eq%' ,null,null,null,null,null,null,'2.1.4',null,N'Bytové a nebytové priestory',N'Kód obce + súpisné číslo + číslo nebytového priestoru');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Spaces/?&$filter=Municipality/Code%20eq%Entrance/HouseNo%20eq%20eq%FlatNo%20eq%' ,null,null,null,null,null,null,'2.1.4',null,N'Bytové a nebytové priestory',N'Kód obce + súpisné číslo + číslo bytu');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/ParcelsC(%)?_24select=%',null,null,null,null,null,null,'2.1.4',null,N'Parcely C',N'Interné ID parcely registra C');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/ParcelsC/?&$filter=CadastralUnit/Code%20eq%Folio/No%20eq%',null,null,null,null,null,null,'2.1.4',null,N'Parcely C',N'Kód k.ú. + číslo listu vlastníctva');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/ParcelsC/?&$filter=CadastralUnit/Code%20eq%No%20eq%',null,null,null,null,null,null,'2.1.4',null,N'Parcely C',N'Kód k.ú. + číslo parcely registra C');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/ParcelsC/?&$filter=Municipality/Code%20eq%Folio/No%20eq%',null,null,null,null,null,null,'2.1.4',null,N'Parcely C',N'Kód obce + číslo listu vlastníctva');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/ParcelsC/?&$filter=Municipality/Code%20eq%No%20eq%',null,null,null,null,null,null,'2.1.4',null,N'Parcely C',N'Kód obce + číslo parcely registra C');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/ParcelsÈ(%)?_24select=%',null,null,null,null,null,null,'2.1.4',null,N'Parcely E',N'Interné ID parcely registra C');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/ParcelsE/?&$filter=CadastralUnit/Code%20eq%Folio/No%20eq%',null,null,null,null,null,null,'2.1.4',null,N'Parcely E',N'Kód k.ú. + číslo listu vlastníctva');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/ParcelsE/?&$filter=CadastralUnit/Code%20eq%No%20eq%',null,null,null,null,null,null,'2.1.4',null,N'Parcely E',N'Kód k.ú. + číslo parcely registra E');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/ParcelsE/?&$filter=Municipality/Code%20eq%Folio/No%20eq%',null,null,null,null,null,null,'2.1.4',null,N'Parcely E',N'Kód obce + číslo listu vlastníctva');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/ParcelsE/?&$filter=Municipality/Code%20eq%No%20eq%',null,null,null,null,null,null,'2.1.4',null,N'Parcely E',N'Kód obce + číslo parcely registra E');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Constructions(%)?_24select=%',null,null,null,null,null,null,'2.1.4',null,N'Stavby',N'Interné ID stavby');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Constructions/?&$filter=CadastralUnit/Code%20eq%Folio/No%20eq%',null,null,null,null,null,null,'2.1.4',null,N'Stavby',N'Kód k.ú. + číslo listu vlastníctva');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Constructions/?&$filter=CadastralUnit/Code%20eq%ParcelsC/any(%',null,null,null,null,null,null,'2.1.4',null,N'Stavby',N'Kód k.ú. + číslo parcely registra C');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Constructions/?&$filter=CadastralUnit/Code%20eq%HouseNo%20eq%',null,null,null,null,null,null,'2.1.4',null,N'Stavby',N'Kód k.ú. + súpisné číslo');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Constructions/?&$filter=Municipality/Code/Code%20eq%Folio/No%20eq%',null,null,null,null,null,null,'2.1.4',null,N'Stavby',N'Kód obce + číslo listu vlastníctva');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Constructions/?&$filter=Municipality/Code/Code%20eq%ParcelsC/any(%',null,null,null,null,null,null,'2.1.4',null,N'Stavby',N'Kód obce + číslo parcely registra C');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Constructions/?&$filter=Municipality/Code/Code%20eq%HouseNo%20eq%',null,null,null,null,null,null,'2.1.4',null,N'Stavby',N'Kód obce + súpisné číslo');

-- Insert service A 2.1.14
INSERT INTO [dbo].[CATServiceParameters]([ServiceCode],[ServiceDescription],[ServiceBasicPrice]) VALUES('2.1.14',N'A.2.1.14 Poskytnutie informácie z KN o súpise stavieb',0.001);
-- Insert pattern
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Spaces/?&$filter=CadastralUnit/Code%20eq%select=Id%',null,null,null,null,null,null,'2.1.4',null  ,N'Súpis bytov a nebytových priestorov',N'Kód k.ú.');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Spaces/?&$filter=Municipality/Code%20eq%select=Id%',null,null,null,null,null,null,'2.1.4',null, N'Súpis bytov a nebytových priestorov',N'Kód obce');    
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Constructions/?&$filter=CadastralUnit/Code%20eq%select=Id%',null,null,null,null,null,null,'2.1.4',null, N'Súpis stavieb', N'Kód k.ú.');
INSERT INTO [dbo].[CATServicePatterns]([PatternLike],[RegExp1Output],[PatternRegExp2],[RegExp2Output],[PatternRegExp3],[RegExp3Output],[PatternDescription],[FKServiceID],[Entity],[Explanation],[DatSelectMethod]) VALUES('%/Constructions/?&$filter=Municipality/Code%20eq%select=Id%',null,null,null,null,null,null,'2.1.4',null, N'Súpis stavieb', N'Kód obce');  